CREATE TABLE IF NOT EXISTS `chat`(
	`id` BIGINT AUTO_INCREMENT NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `id`
		FOREIGN KEY (`id`)
		REFERENCES `member`(`chat_id`)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
		FOREIGN KEY (`id`)
		REFERENCES `messages`(`chat_id`)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `member`(
    `id` BIGINT AUTO_INCREMENT NOT NULL,
	`chat_id` BIGINT NOT NULL,
	`user_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `messages`(
	`id` BIGINT AUTO_INCREMENT NOT NULL,
	`chat_id` BIGINT NOT NULL,
	`content` text NOT NULL,
	`user_id` BIGINT NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `users`(
	`id` BIGINT AUTO_INCREMENT NOT NULL,
	`username` varchar(64) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `id`
		FOREIGN KEY (`id`)
		REFERENCES `messages`('user_id')
		ON DELETE CASCADE
		ON UPDATE CASCADE,
        FOREIGN KEY (`id`)
		REFERENCES `member`('user_id')
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE=InnoDB;